import {JS, TS, JAVA, REACT, LUA, CLOJURE, RUBY, VSC, CPLUS,RAILS, LOVE, GLASSFISH,NETBEANS, UBUNTU, 
        WINDOWS, APPLE, HTML5, CSS3, GRAPHQL, APOLLO, SEMANTIC_UI, NEXTJS, MONGODB, NODEJS, HEROKU, 
        VERCEL, FIREBASE} from './devIcons.js';

export const icons = {
    webtry: [REACT, GRAPHQL, APOLLO, CSS3, VERCEL],
    webtry_back_end: [GRAPHQL, NODEJS, APOLLO, MONGODB, HEROKU],
    socialMedia: [REACT, GRAPHQL, APOLLO, SEMANTIC_UI, VERCEL],
    socialMedia_back_end: [GRAPHQL, NODEJS, APOLLO, MONGODB, HEROKU],
    CRM: [REACT, GRAPHQL, APOLLO, NEXTJS, VERCEL],
    CRM_back_end: [GRAPHQL, NODEJS, APOLLO, MONGODB, HEROKU],
    theRosa: [JS, HTML5, CSS3, VSC, APPLE, FIREBASE],
    photoSite: [REACT, TS, VSC, APPLE,FIREBASE],
    burger: [JS, REACT, VSC, UBUNTU, FIREBASE],
    setsStore: [REACT, VSC, APPLE, CSS3],
    marsExp: [LUA, VSC, LOVE, UBUNTU],
    connect4: [LUA, VSC, LOVE, UBUNTU],
    bbreaker: [CPLUS, UBUNTU],
    restfb: [JAVA, GLASSFISH,NETBEANS, WINDOWS],
    wandw: [JS, VSC, RUBY, UBUNTU],
    fourClojure: [VSC, CLOJURE, UBUNTU],
    designPatt: [RUBY, RAILS, VSC, UBUNTU],
}
